name: example
description: An example command line application that uses cli_readme_builder
version: 1.0.0

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  args: ^2.3.1
  path: ^1.8.3

dev_dependencies:
  cli_readme_builder:
    path: ../
  lints: ^2.0.1
  build_runner: ^2.3.3
