# Read about `build.yaml` at https://pub.dev/packages/build_config
targets:
  $default:
    builders:
      cli_readme_builder:
        options:
          output: my_output_file.md
        enabled: false

builders:
  cli_readme_builder:
    import: "package:cli_readme_builder/readme_builder.dart"
    builder_factories: ["cliReadmeBuilder"]
    build_extensions: {"pubspec.yaml": ["README.g.md"]}
    defaults:
      options:
        output: "README.g.md"
        verbose_logging: false
    build_to: source
    auto_apply: dependents
