name: cli_readme_builder
description: A builder to automate the process of creating a README for Dart console applications
version: 2.0.0
repository: https://github.com/m-skolnick/cli_readme_builder

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  args: ^2.4.1
  build: ^2.1.0
  mason_logger: ^0.2.5
  meta: ^1.7.0
  path: ^1.8.2
  process_run: ^0.13.0
  pubspec_parse: ^1.0.0

dev_dependencies:
  build_runner: ^2.0.0
  build_test: ^2.0.0
  build_verify: '>=2.0.0 <4.0.0'
  checked_yaml: ^2.0.0
  coverage: ^1.6.3
  lints: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.2.0
